messanger/urls.py
from django.urls import path

from . import views

app_name = 'messanger'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
    path('auth/ajax_login/', views.ajax_login, name='ajax_login'),
    path('auth/logout/', views.logout, name='logout'),
    path('db/ajax_new_room/', views.ajax_new_room, name='ajax_new_room'),
    path('db/ajax_add_user_to_room/', views.ajax_add_user_to_room, name='ajax_add_user_to_room'),
]

messanger/models.py
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    username = models.CharField(max_length=255)
    room = models.CharField(max_length=255)
    content = models.TextField()
    iv = models.CharField(max_length=255, default='no_key')
    is_important = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)


class Room(models.Model):
    room = models.CharField(max_length=255)
    host_user = models.ForeignKey(User, on_delete=models.CASCADE)
    allowed_users = models.CharField(max_length=255)

    def allowed_users_as_list(self):
        return self.allowed_users.split('|')


messanger/views.py
from django.contrib import auth
from django.http import JsonResponse
from django.shortcuts import redirect, HttpResponse
from django.shortcuts import render

from .models import Message, Room
from django.contrib.auth.models import User


def index(request):
    return render(request, 'chat/index.html')


def room(request, room_name):
    if request.user.is_authenticated:
        username = request.user.username
        messages = Message.objects.filter(room=room_name)
        user = request.user.username
        user_rooms = Room.objects.values_list('room', 'allowed_users')
        user_rooms = {str(room_number): allowed_users.split('|') for room_number, allowed_users in user_rooms}
        user_rooms = [key for key, vals in user_rooms.items() if str(user) in vals]
        all_users = User.objects.values('username')
        super_user = Room.objects.filter(room=room_name)[0]
        if (request.user in all_users) or (room_name == 'publicChat') or request.user.is_staff:
            return render(request, 'chat/room.html',
                          {'room_name': room_name, 'username': username, 'messages': messages, 'user_rooms': user_rooms,
                           'all_users': all_users, 'superuser': super_user})
        else:
            return HttpResponse('You have no access')
    else:
        return redirect('messanger:index')


def ajax_login(request):
    next = ''
    if request.GET:
        next = request.GET['next']
    if request.method == 'POST':
        username = request.POST.get('username', 'anon')
        password = request.POST.get('password', '')
        #room_name = request.POST.get('roomname', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            if next != '':
                #  return render(request, 'chat/room.html', {'room_name': room_name, 'username': user.username, 'password': user.password})
                return JsonResponse({'s': 'logined_next'}, status=200)
            else:
                return JsonResponse({'s': 'logined_done'}, status=200)
        else:
            login_error = 'Неправильный логин или пароль'
            return HttpResponse(login_error, status=400)
    else:
        return HttpResponse('Ошибка запроса', status=500)


def logout(request):
    auth.logout(request)
    return redirect('messanger:index')


def ajax_new_room(request):
    if request.method == 'POST':
        new_room_users = request.POST.get('userNewRoom')
        new_room_number = request.POST.get('newRoom')
        if Room.objects.filter(room=new_room_number):
            return JsonResponse({'error_message': 'Room already exist'}, status=403)
        else:
            new_room = Room(room=new_room_number, host_user=User.objects.get(id=request.user.id),
                            allowed_users=new_room_users)
            new_room.save()
            return JsonResponse({'success_message': f'Room {new_room_number} created'}, status=200)
    else:
        return JsonResponse({'error_message': 'Why are you using GET-request???'}, status=403)


def ajax_add_user_to_room(request):
    if request.method == 'POST':
        new_user = request.POST.get('newUser')
        updating_room = Room.objects.get(room=request.POST.get('room'))
        new_user = list(filter(lambda x: x not in updating_room.allowed_users, new_user.split('|')))
        new_user = '|'.join(new_user)
        updating_room.allowed_users = '|'.join([updating_room.allowed_users, new_user])
        updating_room.save()
        return JsonResponse({'success_message': 'User(s) added'}, status=200)
    else:
        return JsonResponse({'error_message': 'Why are you using GET-request???'}, status=403)

templates/chat/fake_error_endpoint.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ login_error }}
</body>
</html>

templates/chat/index.html
<!DOCTYPE html>

<html>
<title>Login</title>
<style>
    body {
        background-color: #ffc;
        width: 30%;
        margin: 20px auto;
        color: #410c65;
    }

    .header {
        position: fixed;
        padding: 10px 0;
        height: 50px;
    }

    h1 {
        margin: 3px 0;
    }

    .start {
        display: block;
        padding-top: 80px;
    }

    .field {
        max-width: 400px;
        margin: auto;
    }

    p {
        margin: 0 0 7px;
        font-size: 16px;
    }

    input {
        font-family: "Roboto", sans-serif;
        background: #f2f2f2;
        outline: 0;
        border-color: #dbdbdb;
        margin: 0 0 15px;
        width: 100%;
        padding: 15px;
        box-sizing: border-box;
        font-size: 14px;
        border-radius: 5px;
        transition: all 0.3ms;
        box-shadow: inset 0 0.065em 0.165em rgb(10 10 10 / 5%);
    }

    input:focus {
        border-color: #7e2caa;
    }

    .control-button {
        margin-top: 20px;
    }

    .button {
        font-family: "Roboto", sans-serif;
        text-transform: uppercase;
        background: #69218f;
        border: 0;
        padding: 15px 30px;
        color: #FFFFFF;
        font-size: 14px;
        transition: all 0.3ms;
        cursor: pointer;
        border-radius: 5px;
    }

    .button:hover, .button:active, .button:focus {
        background: #410c65;
    }

    .error-text {
        margin-top: 20px;
        font-size: 16px;
        padding: 10px;
        border-radius: 5px;
        background-color: #8d2f2f;
        color: #dcc8ef;
    }

</style>

<head>
    <meta charset="utf-8"/>
    <title>Chat Box</title>
</head>

<body>
{% csrf_token %}
<header class="header">
    <h1>ChatBox</h1>
</header>
<div class="start">
    <div class="column" id="column">

        <div class="field">
            <p>Username</p>
            <div class="control">
                <input class="input" type="text" placeholder="Username" id="username-input">
            </div>
        </div>
        <div class="field">
            <p>Password</p>
            <div class="control">
                <input class="input" type="password" placeholder="Password" id="password-input">
            </div>
        </div>
        <div class="field">
            <div class="control-button">
                <a class="button" id="room-name-submit">Submit</a>
            </div>
        </div>
    </div>
</div>
</body>
{% load static %}
<script src="{% static 'jquery-3.6.0.js' %}"></script>
<script>

    $(document).ready(function () {
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length +
                            1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        function sameOrigin(url) {
            var host = document.location.host;
            var protocol = document.location.protocol;
            var sr_origin = '//' + host;
            var origin = protocol + sr_origin;
            return (url == origin || url.slice(0, origin.length + 1) == origin + '/') || (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                !(/^(\/\/|http:|https:).*/.test(url));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    xhr.setRequestHeader('X-CSRFToken',
                        $('input[name="csrfmiddlewaretoken"]').val());
                }
            }
        });
        $('#room-name-submit').click(function () {
            let url = '/messanger/' + 'publicChat';
            $.ajax({
                type: "POST",
                url: "{% url 'messanger:ajax_login' %}",
                data: {
                    "username": document.querySelector('#username-input').value,
                    "password": document.querySelector('#password-input').value,
                    //"roomname": document.querySelector('#room-name-input').value,
                },
                success: function (data) {
                    //alert('Done')
                    //makeKeyFiles(document.querySelector('#username-input').value, document.querySelector('#room-name-input').value)
                    $(location).attr('href', url);
                    //window.location.replace(roomName);
                },
                error: function (data) {
                    // предупредим об ошибке
                    if (document.querySelector('#error-text')) document.querySelector('#column').removeChild(errorText)
                    if (data.status == 400) {
                        let errorText = document.createElement('div')
                        document.querySelector('#column').appendChild(errorText)
                        errorText.className = "error-text"
                        errorText.id = "error-text"
                        errorText.innerText = "Неверно введён логин или пароль"
                    }
                }

                //alert(data.status);

        });
        //alert('fsdsdsddf');
    });
    })
    ;
    document.querySelector('#room-name-input').focus();

    document.querySelector('#room-name-submit').onclick = function (e) {
        var roomName = document.querySelector('#room-name-input').value;
        var userName = document.querySelector('#username-input').value;
        var password = document.querySelector('#password-input').value;


        //window.location.replace(roomName + '/?username=' + userName);
        //
    };
</script>
</html>